# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer:${ADMINER_VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-app}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      ADMINER_DEFAULT_DATABASE: ${POSTGRES_DB:-app}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-nette}
      ADMINER_PLUGINS: tables-filter tinymce
    depends_on:
      - database
